### ISSUE TITLE
Error with setup when using Password.

### ISSUE THREAD

**Issue by hackdefendr** [trustedsec/tap#5]
Everything seems to run fine under Ubuntu 18.04 until the password encrypting phase.  See below:
```
[*] Encrypting the password now..
Traceback (most recent call last):
  File "setup.py", line 206, in <module>
    password = encryptAES(password)
  File "setup.py", line 77, in encryptAES
    return str(aes) + "::::" + secret
TypeError: must be str, not bytes
```

**Comment by HackingDave** [comment]
Thanks, will take a peek shortly.

**Comment by HackingDave** [comment]
Fixed, thanks!
